name: near_share
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.1
  google_sign_in: 6.3.0
  provider: ^6.1.1
  google_fonts: ^8.0.0
  font_awesome_flutter: ^10.6.0
  pinput: ^6.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  iconsax: ^0.0.8
  iconsax_plus: ^1.0.0
  share_plus: ^12.0.1
  image_picker: ^1.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_db.json
